# Generated by Django 5.0.1 on 2024-01-29 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_details_feature_addtocart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Detail',
        ),
    ]
