# Generated by Django 5.0.1 on 2024-01-31 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_purchasedproduct_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedproduct',
            old_name='cart',
            new_name='add_to_cart',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='purchased_product',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='purchased_quantity',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchasedproduct',
            name='user',
        ),
        migrations.AlterField(
            model_name='addtocart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
